#Correctly background processes
setopt nohup

#Stop zsh from stupidly asking me to correct vim to .vim
unsetopt correctall

#Bind my shit
bindkey -s "\eu" "cd ..\n"  #cd up

#Turn off share history
unsetopt share_history

#zmv is the bee's-knees
autoload -U zmv

# Save ssh password within a terminal
eval $(ssh-agent) 2>&1 >/dev/null
trap "kill $SSH_AGENT_PID" 0
